name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    
    - name: Setup CI Environment
      uses: yetanalytics/actions/setup-env@v0.0.4
    
    - name: Run tests
      run: make test
